theme: jekyll-theme-minimal
title: Ziqi Gao
description: Master @ UW CSE RAIVN Lab & Tsinghua Pervasive HCI Lab
logo: img/ziqigao.jpg
Google Scholar: https://scholar.google.com/citations?user=ZDBlmEAAAAAJ&hl=zh-CN&oi=sra
